[package]
name = "aramid"
version = "0.2.3"
edition = "2021"
description = "Synthetic fibers"
homepage = "https://github.com/mira-merkell/aramid"
license = "MIT"
readme = "README.md"
repository = "https://github.com/mira-merkell/aramid.git"

[dependencies]

[dev-dependencies]

